# Generated by Django 4.2 on 2023-07-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_alter_avatar_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatares'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='images')),
                ('state', models.BooleanField(default=False, verbose_name='Active')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='libreria.tag')),
            ],
        ),
    ]
