# Generated by Django 4.2 on 2023-07-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
