# Generated by Django 4.2 on 2023-07-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_remove_comment_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
