# Generated by Django 4.2 on 2023-07-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
